---
title: "The assessment"
subtitle: "Coming soon" 
author: "Reny Baykova"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    selt_contained: true
    nature:
      highlightStyle: github
      highlightLines: true 
      countIncrementalSlides: false
      beforeInit: "macros.js"
---

<!-- 
vim: set ft=markdown tw=80 spell spelllang=en_gb:
vim: set conceallevel=0 foldlevel=1:
-->
```{r, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


```{r, echo=FALSE, eval=TRUE}
library(xaringanthemer)

style_duo_accent(
 primary_color = "#003b49",
secondary_color = "#1d4289",
header_font_google = google_font("Cabin"),
text_font_google   = google_font("Noto Sans", "300", "300i"),
code_font_google   = google_font("Fira Mono"),
colors = c(
red = "#d3273e",
purple = "#5d3754s",
orange = "#dc582a",
green = "#007a78",
white = "#FFFFFF",
blue = "#1d4289"
)
)
xaringanthemer::style_extra_css(
  list(".title-slide" = list(
   # "background-image" =
   #   "url(https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/University_of_Sussex_Logo.svg/480px-University_of_Sussex_Logo.svg.png)",
  "background-position" =  "95% 95%",
 "background-size" = "180px",
  "border" = "10px solid #013035",
  "background-color" = "#FFFFFF"
  ),
 ".title-slide h1" = list(
  "padding-top" = "0px",
  "font-size" = "60px",
  "text-align" = "left",
  "padding-bottom" = "18px",
  "margin-bottom" = "18px",
  "margin-top" = "0px",
  "color" = "#003b49"
 ),
 ".title-slide h2" = list(
   "font-size" = "40px",
   "text-align" = "left",
   "padding-top" = "10px",
   "margin-top" = "0px",
   "color" = "#003b49"
 ),
 ".title-slide h3" = list(
   "font-size" = "30px",
   "color" = "#26272A",
   "text-align" = "left",
   "text-shadow" = "none",
   "padding" = "0px",
   "margin" = "0px",
   "line-height" = "1"),
 ".footnote" = list(
   "font-size" = ".6em"
 ),
   ".section h1" = list(
    "padding" = "auto",
    "display" = "block",
    "margin-left" = "auto",
    "margin-right" = "auto",
    "padding-top" = "250px",
    "vertical-align" = "auto",
    "align-items" = "center",
    "font-size" = "40px"
   ),
".section .remark-slide-number" = list(
   "display" = "none"),
   "pre" = list("border-style" = "solid",
   "border-width" = "1px",
   "border-color" = "lightgrey",
   "padding" = "5px",
   "border-radius" = "3px")
))

```


```{r broadcast, echo=FALSE}
xaringanExtra::use_broadcast()
xaringanExtra::use_share_again()
xaringanExtra::use_xaringan_extra(c("tile_view", "animate_css", "tachyons"))
```


```{r, echo=FALSE, eval=FALSE}
# I'll add some meta data later
# library(metathis)
# meta() %>%
#   meta_description(desc)
```

### Assessment to be added soon

We are still waiting for the assessment to be approved. 
Information to be added soon. 
